name: Dividi catalogo per brand

on:
  schedule:
    - cron: "40 5,17 * * *"  # 10 minuti dopo l'altro
  workflow_dispatch:

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      - name: Clona la repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa unidecode
        run: pip install unidecode

      - name: Esegui script per dividere i file per brand
        run: python dividi_per_brand.py

      - name: Commit dei file /brand
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add brand || echo "Nessuna modifica"
          git commit -m "Aggiornati file divisi per brand" || echo "Niente da committare"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
