name: Genera catalogo_light.json

on:
  schedule:
    - cron: "30 5,17 * * *"  # alle 7:30 e 19:30 italiane
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests

      - name: Genera catalogo_light.json
        run: python crea_catalogo_light.py

      - name: Commit e push catalogo_light.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add catalogo_light.json
          git commit -m "Aggiornamento catalogo_light automatico" || echo "Nessuna modifica"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
