name: Esegui app.py due volte al giorno

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'
    - cron: '30 17 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa le dipendenze
        run: |
          pip install -r requirements.txt

      - name: Esegui app.py
        run: |
          python app.py
