name: Aggiorna catalogo due volte al giorno

on:
  schedule:
    - cron: "30 5,17 * * *"  # 7:30 e 19:30 italiane
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona la repo con token personale
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa richieste
        run: pip install requests

      - name: Esegui script Python
        run: python estrai_catalogo.py

      - name: Fai il commit del nuovo catalogo.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add catalogo.json || echo "Nessuna modifica"
          git commit -m "Aggiornamento automatico catalogo" || echo "Niente da committare"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
   
